// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDurationParams creates a new DurationParams object
// with the default values initialized.
func NewDurationParams() *DurationParams {
	var (
		userDefault = string("current")
	)
	return &DurationParams{
		User: userDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewDurationParamsWithTimeout creates a new DurationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDurationParamsWithTimeout(timeout time.Duration) *DurationParams {
	var (
		userDefault = string("current")
	)
	return &DurationParams{
		User: userDefault,

		timeout: timeout,
	}
}

// NewDurationParamsWithContext creates a new DurationParams object
// with the default values initialized, and the ability to set a context for a request
func NewDurationParamsWithContext(ctx context.Context) *DurationParams {
	var (
		userDefault = string("current")
	)
	return &DurationParams{
		User: userDefault,

		Context: ctx,
	}
}

// NewDurationParamsWithHTTPClient creates a new DurationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDurationParamsWithHTTPClient(client *http.Client) *DurationParams {
	var (
		userDefault = string("current")
	)
	return &DurationParams{
		User:       userDefault,
		HTTPClient: client,
	}
}

/*DurationParams contains all the parameters to send to the API endpoint
for the duration operation typically these are written to a http.Request
*/
type DurationParams struct {

	/*Branches
	  Only show durations for these branches; comma separated list of branch names.

	*/
	Branches *string
	/*Date
	  Requested day; Durations will be returned from 12am until 11:59pm in user's timezone for this day.

	*/
	Date strfmt.Date
	/*Project
	  Only show durations for this project.

	*/
	Project *string
	/*User
	  ID of the user to obtain

	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the duration params
func (o *DurationParams) WithTimeout(timeout time.Duration) *DurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the duration params
func (o *DurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the duration params
func (o *DurationParams) WithContext(ctx context.Context) *DurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the duration params
func (o *DurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the duration params
func (o *DurationParams) WithHTTPClient(client *http.Client) *DurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the duration params
func (o *DurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranches adds the branches to the duration params
func (o *DurationParams) WithBranches(branches *string) *DurationParams {
	o.SetBranches(branches)
	return o
}

// SetBranches adds the branches to the duration params
func (o *DurationParams) SetBranches(branches *string) {
	o.Branches = branches
}

// WithDate adds the date to the duration params
func (o *DurationParams) WithDate(date strfmt.Date) *DurationParams {
	o.SetDate(date)
	return o
}

// SetDate adds the date to the duration params
func (o *DurationParams) SetDate(date strfmt.Date) {
	o.Date = date
}

// WithProject adds the project to the duration params
func (o *DurationParams) WithProject(project *string) *DurationParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the duration params
func (o *DurationParams) SetProject(project *string) {
	o.Project = project
}

// WithUser adds the user to the duration params
func (o *DurationParams) WithUser(user string) *DurationParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the duration params
func (o *DurationParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *DurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Branches != nil {

		// query param branches
		var qrBranches string
		if o.Branches != nil {
			qrBranches = *o.Branches
		}
		qBranches := qrBranches
		if qBranches != "" {
			if err := r.SetQueryParam("branches", qBranches); err != nil {
				return err
			}
		}

	}

	// query param date
	qrDate := o.Date
	qDate := qrDate.String()
	if qDate != "" {
		if err := r.SetQueryParam("date", qDate); err != nil {
			return err
		}
	}

	if o.Project != nil {

		// query param project
		var qrProject string
		if o.Project != nil {
			qrProject = *o.Project
		}
		qProject := qrProject
		if qProject != "" {
			if err := r.SetQueryParam("project", qProject); err != nil {
				return err
			}
		}

	}

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
