// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProjectsParams creates a new ProjectsParams object
// with the default values initialized.
func NewProjectsParams() *ProjectsParams {
	var (
		userDefault = string("current")
	)
	return &ProjectsParams{
		User: userDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectsParamsWithTimeout creates a new ProjectsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectsParamsWithTimeout(timeout time.Duration) *ProjectsParams {
	var (
		userDefault = string("current")
	)
	return &ProjectsParams{
		User: userDefault,

		timeout: timeout,
	}
}

// NewProjectsParamsWithContext creates a new ProjectsParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectsParamsWithContext(ctx context.Context) *ProjectsParams {
	var (
		userDefault = string("current")
	)
	return &ProjectsParams{
		User: userDefault,

		Context: ctx,
	}
}

// NewProjectsParamsWithHTTPClient creates a new ProjectsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectsParamsWithHTTPClient(client *http.Client) *ProjectsParams {
	var (
		userDefault = string("current")
	)
	return &ProjectsParams{
		User:       userDefault,
		HTTPClient: client,
	}
}

/*ProjectsParams contains all the parameters to send to the API endpoint
for the projects operation typically these are written to a http.Request
*/
type ProjectsParams struct {

	/*User
	  ID of the user to obtain

	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the projects params
func (o *ProjectsParams) WithTimeout(timeout time.Duration) *ProjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the projects params
func (o *ProjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the projects params
func (o *ProjectsParams) WithContext(ctx context.Context) *ProjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the projects params
func (o *ProjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the projects params
func (o *ProjectsParams) WithHTTPClient(client *http.Client) *ProjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the projects params
func (o *ProjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the projects params
func (o *ProjectsParams) WithUser(user string) *ProjectsParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the projects params
func (o *ProjectsParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
