// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUserParams creates a new UserParams object
// with the default values initialized.
func NewUserParams() *UserParams {
	var (
		userDefault = string("current")
	)
	return &UserParams{
		User: userDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewUserParamsWithTimeout creates a new UserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserParamsWithTimeout(timeout time.Duration) *UserParams {
	var (
		userDefault = string("current")
	)
	return &UserParams{
		User: userDefault,

		timeout: timeout,
	}
}

// NewUserParamsWithContext creates a new UserParams object
// with the default values initialized, and the ability to set a context for a request
func NewUserParamsWithContext(ctx context.Context) *UserParams {
	var (
		userDefault = string("current")
	)
	return &UserParams{
		User: userDefault,

		Context: ctx,
	}
}

// NewUserParamsWithHTTPClient creates a new UserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUserParamsWithHTTPClient(client *http.Client) *UserParams {
	var (
		userDefault = string("current")
	)
	return &UserParams{
		User:       userDefault,
		HTTPClient: client,
	}
}

/*UserParams contains all the parameters to send to the API endpoint
for the user operation typically these are written to a http.Request
*/
type UserParams struct {

	/*User
	  ID of the user to obtain

	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the user params
func (o *UserParams) WithTimeout(timeout time.Duration) *UserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user params
func (o *UserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user params
func (o *UserParams) WithContext(ctx context.Context) *UserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user params
func (o *UserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user params
func (o *UserParams) WithHTTPClient(client *http.Client) *UserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user params
func (o *UserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the user params
func (o *UserParams) WithUser(user string) *UserParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the user params
func (o *UserParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *UserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
