// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUserAgentsParams creates a new UserAgentsParams object
// with the default values initialized.
func NewUserAgentsParams() *UserAgentsParams {
	var (
		userDefault = string("current")
	)
	return &UserAgentsParams{
		User: userDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewUserAgentsParamsWithTimeout creates a new UserAgentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserAgentsParamsWithTimeout(timeout time.Duration) *UserAgentsParams {
	var (
		userDefault = string("current")
	)
	return &UserAgentsParams{
		User: userDefault,

		timeout: timeout,
	}
}

// NewUserAgentsParamsWithContext creates a new UserAgentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewUserAgentsParamsWithContext(ctx context.Context) *UserAgentsParams {
	var (
		userDefault = string("current")
	)
	return &UserAgentsParams{
		User: userDefault,

		Context: ctx,
	}
}

// NewUserAgentsParamsWithHTTPClient creates a new UserAgentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUserAgentsParamsWithHTTPClient(client *http.Client) *UserAgentsParams {
	var (
		userDefault = string("current")
	)
	return &UserAgentsParams{
		User:       userDefault,
		HTTPClient: client,
	}
}

/*UserAgentsParams contains all the parameters to send to the API endpoint
for the user agents operation typically these are written to a http.Request
*/
type UserAgentsParams struct {

	/*User
	  ID of the user to obtain

	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the user agents params
func (o *UserAgentsParams) WithTimeout(timeout time.Duration) *UserAgentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user agents params
func (o *UserAgentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user agents params
func (o *UserAgentsParams) WithContext(ctx context.Context) *UserAgentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user agents params
func (o *UserAgentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user agents params
func (o *UserAgentsParams) WithHTTPClient(client *http.Client) *UserAgentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user agents params
func (o *UserAgentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the user agents params
func (o *UserAgentsParams) WithUser(user string) *UserAgentsParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the user agents params
func (o *UserAgentsParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *UserAgentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
