// Code generated by go-swagger; DO NOT EDIT.

package stats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCurrentUserStatsParams creates a new CurrentUserStatsParams object
// with the default values initialized.
func NewCurrentUserStatsParams() *CurrentUserStatsParams {
	var (
		rangeVarDefault = string("last_7_days")
	)
	return &CurrentUserStatsParams{
		Range: rangeVarDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewCurrentUserStatsParamsWithTimeout creates a new CurrentUserStatsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCurrentUserStatsParamsWithTimeout(timeout time.Duration) *CurrentUserStatsParams {
	var (
		rangeVarDefault = string("last_7_days")
	)
	return &CurrentUserStatsParams{
		Range: rangeVarDefault,

		timeout: timeout,
	}
}

// NewCurrentUserStatsParamsWithContext creates a new CurrentUserStatsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCurrentUserStatsParamsWithContext(ctx context.Context) *CurrentUserStatsParams {
	var (
		rangeDefault = string("last_7_days")
	)
	return &CurrentUserStatsParams{
		Range: rangeDefault,

		Context: ctx,
	}
}

// NewCurrentUserStatsParamsWithHTTPClient creates a new CurrentUserStatsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCurrentUserStatsParamsWithHTTPClient(client *http.Client) *CurrentUserStatsParams {
	var (
		rangeDefault = string("last_7_days")
	)
	return &CurrentUserStatsParams{
		Range:      rangeDefault,
		HTTPClient: client,
	}
}

/*CurrentUserStatsParams contains all the parameters to send to the API endpoint
for the current user stats operation typically these are written to a http.Request
*/
type CurrentUserStatsParams struct {

	/*Range
	  Range activity

	*/
	Range string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the current user stats params
func (o *CurrentUserStatsParams) WithTimeout(timeout time.Duration) *CurrentUserStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the current user stats params
func (o *CurrentUserStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the current user stats params
func (o *CurrentUserStatsParams) WithContext(ctx context.Context) *CurrentUserStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the current user stats params
func (o *CurrentUserStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the current user stats params
func (o *CurrentUserStatsParams) WithHTTPClient(client *http.Client) *CurrentUserStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the current user stats params
func (o *CurrentUserStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRange adds the rangeVar to the current user stats params
func (o *CurrentUserStatsParams) WithRange(rangeVar string) *CurrentUserStatsParams {
	o.SetRange(rangeVar)
	return o
}

// SetRange adds the range to the current user stats params
func (o *CurrentUserStatsParams) SetRange(rangeVar string) {
	o.Range = rangeVar
}

// WriteToRequest writes these params to a swagger request
func (o *CurrentUserStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param range
	if err := r.SetPathParam("range", o.Range); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
