// Code generated by go-swagger; DO NOT EDIT.

package stats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new stats API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for stats API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CurrentUserStats A user's coding activity for the given time range. range can be one of last_7_days, last_30_days, last_6_months, or last_year.
*/
func (a *Client) CurrentUserStats(params *CurrentUserStatsParams, authInfo runtime.ClientAuthInfoWriter) (*CurrentUserStatsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCurrentUserStatsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "currentUserStats",
		Method:             "GET",
		PathPattern:        "/users/current/stats/{range}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CurrentUserStatsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CurrentUserStatsOK), nil

}

/*
GetUserStats A user's coding activity for the given time range. range can be one of last_7_days, last_30_days, last_6_months, or last_year.
*/
func (a *Client) GetUserStats(params *GetUserStatsParams, authInfo runtime.ClientAuthInfoWriter) (*GetUserStatsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetUserStatsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getUserStats",
		Method:             "GET",
		PathPattern:        "/users/{user}/stats/{range}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetUserStatsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetUserStatsOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
