// Code generated by go-swagger; DO NOT EDIT.

package user_agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUserAgentsParams creates a new GetUserAgentsParams object
// with the default values initialized.
func NewGetUserAgentsParams() *GetUserAgentsParams {
	var ()
	return &GetUserAgentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserAgentsParamsWithTimeout creates a new GetUserAgentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserAgentsParamsWithTimeout(timeout time.Duration) *GetUserAgentsParams {
	var ()
	return &GetUserAgentsParams{

		timeout: timeout,
	}
}

// NewGetUserAgentsParamsWithContext creates a new GetUserAgentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUserAgentsParamsWithContext(ctx context.Context) *GetUserAgentsParams {
	var ()
	return &GetUserAgentsParams{

		Context: ctx,
	}
}

// NewGetUserAgentsParamsWithHTTPClient creates a new GetUserAgentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUserAgentsParamsWithHTTPClient(client *http.Client) *GetUserAgentsParams {
	var ()
	return &GetUserAgentsParams{
		HTTPClient: client,
	}
}

/*GetUserAgentsParams contains all the parameters to send to the API endpoint
for the get user agents operation typically these are written to a http.Request
*/
type GetUserAgentsParams struct {

	/*User
	  ID of the user to obtain

	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user agents params
func (o *GetUserAgentsParams) WithTimeout(timeout time.Duration) *GetUserAgentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user agents params
func (o *GetUserAgentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user agents params
func (o *GetUserAgentsParams) WithContext(ctx context.Context) *GetUserAgentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user agents params
func (o *GetUserAgentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user agents params
func (o *GetUserAgentsParams) WithHTTPClient(client *http.Client) *GetUserAgentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user agents params
func (o *GetUserAgentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the get user agents params
func (o *GetUserAgentsParams) WithUser(user string) *GetUserAgentsParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the get user agents params
func (o *GetUserAgentsParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserAgentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
