// Code generated by go-swagger; DO NOT EDIT.

package user_agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/will7200/wakatime/models"
)

// GetUserAgentsReader is a Reader for the GetUserAgents structure.
type GetUserAgentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserAgentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUserAgentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetUserAgentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetUserAgentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUserAgentsOK creates a GetUserAgentsOK with default headers values
func NewGetUserAgentsOK() *GetUserAgentsOK {
	return &GetUserAgentsOK{}
}

/*GetUserAgentsOK handles this case with default header values.

List of plugins.
*/
type GetUserAgentsOK struct {
	Payload *GetUserAgentsOKBody
}

func (o *GetUserAgentsOK) Error() string {
	return fmt.Sprintf("[GET /users/{user}/user_agents][%d] getUserAgentsOK  %+v", 200, o.Payload)
}

func (o *GetUserAgentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetUserAgentsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserAgentsUnauthorized creates a GetUserAgentsUnauthorized with default headers values
func NewGetUserAgentsUnauthorized() *GetUserAgentsUnauthorized {
	return &GetUserAgentsUnauthorized{}
}

/*GetUserAgentsUnauthorized handles this case with default header values.

The request requires authentication, or your authentication was invalid.
*/
type GetUserAgentsUnauthorized struct {
	Payload *models.Error
}

func (o *GetUserAgentsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /users/{user}/user_agents][%d] getUserAgentsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetUserAgentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserAgentsNotFound creates a GetUserAgentsNotFound with default headers values
func NewGetUserAgentsNotFound() *GetUserAgentsNotFound {
	return &GetUserAgentsNotFound{}
}

/*GetUserAgentsNotFound handles this case with default header values.

The resource does not exist.
*/
type GetUserAgentsNotFound struct {
}

func (o *GetUserAgentsNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{user}/user_agents][%d] getUserAgentsNotFound ", 404)
}

func (o *GetUserAgentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetUserAgentsOKBody get user agents o k body
swagger:model GetUserAgentsOKBody
*/
type GetUserAgentsOKBody struct {

	// data
	Data []*models.UserAgents `json:"data"`
}

// Validate validates this get user agents o k body
func (o *GetUserAgentsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetUserAgentsOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getUserAgentsOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetUserAgentsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserAgentsOKBody) UnmarshalBinary(b []byte) error {
	var res GetUserAgentsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
