// Code generated by go-swagger; DO NOT EDIT.

package user_agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new user agents API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for user agents API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CurrentUserAgents List of plugins which have sent data for this user.
*/
func (a *Client) CurrentUserAgents(params *CurrentUserAgentsParams, authInfo runtime.ClientAuthInfoWriter) (*CurrentUserAgentsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCurrentUserAgentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "currentUserAgents",
		Method:             "GET",
		PathPattern:        "/users/current/user_agents",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CurrentUserAgentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CurrentUserAgentsOK), nil

}

/*
GetUserAgents List of plugins which have sent data for this user.
*/
func (a *Client) GetUserAgents(params *GetUserAgentsParams, authInfo runtime.ClientAuthInfoWriter) (*GetUserAgentsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetUserAgentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getUserAgents",
		Method:             "GET",
		PathPattern:        "/users/{user}/user_agents",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetUserAgentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetUserAgentsOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
