// Code generated by go-swagger; DO NOT EDIT.

package internal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// BestDay best day
// swagger:model best_day
type BestDay struct {

	// date
	Date Date `json:"date,omitempty"`

	// total seconds
	TotalSeconds int64 `json:"total_seconds,omitempty"`
}

// Validate validates this best day
func (m *BestDay) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BestDay) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BestDay) UnmarshalBinary(b []byte) error {
	var res BestDay
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
