// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// Range range
// swagger:model range
type Range string

const (

	// RangeLast7Days captures enum value "last_7_days"
	RangeLast7Days Range = "last_7_days"

	// RangeLast30Days captures enum value "last_30_days"
	RangeLast30Days Range = "last_30_days"

	// RangeLast6Months captures enum value "last_6_months"
	RangeLast6Months Range = "last_6_months"

	// RangeLastYear captures enum value "last_year"
	RangeLastYear Range = "last_year"
)

// for schema
var rangeEnum []interface{}

func init() {
	var res []Range
	if err := json.Unmarshal([]byte(`["last_7_days","last_30_days","last_6_months","last_year"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		rangeEnum = append(rangeEnum, v)
	}
}

func (m Range) validateRangeEnum(path, location string, value Range) error {
	if err := validate.Enum(path, location, value, rangeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this range
func (m Range) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateRangeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
