// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// StatsCategory stats category
// swagger:model stats_category
type StatsCategory struct {

	// digital
	Digital string `json:"digital,omitempty"`

	// hours
	Hours int64 `json:"hours,omitempty"`

	// minutes
	Minutes int64 `json:"minutes,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// percent
	Percent float64 `json:"percent,omitempty"`

	// seconds
	Seconds int64 `json:"seconds,omitempty"`

	// text
	Text string `json:"text,omitempty"`

	// total seconds
	TotalSeconds int64 `json:"total_seconds,omitempty"`
}

// Validate validates this stats category
func (m *StatsCategory) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StatsCategory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StatsCategory) UnmarshalBinary(b []byte) error {
	var res StatsCategory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
